import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const translations = {
  pt: {
    // Navigation
    nav_home: 'Início',
    nav_services: 'Serviços',
    nav_gallery: 'Galeria',
    nav_shop: 'Loja',
    nav_bookings: 'Reservas',
    nav_contact: 'Contactos',
    
    // Auth
    login: 'Entrar',
    logout: 'Terminar Sessão',
    my_account: 'Minha Conta',
    
    // Home - Hero
    hero_badge: 'Centro Equestre de Excelência',
    hero_title: 'Picadeiro',
    hero_title_highlight: 'Quinta da Horta',
    hero_description: 'Descubra a arte da equitação com o Bi-Campeão do Mundo Gilberto Filipe. Oferecemos aulas personalizadas e experiências únicas com cavalos num ambiente natural e acolhedor.',
    hero_cta_primary: 'Reservar Aula',
    hero_cta_secondary: 'Conhecer Serviços',
    hero_stat_1: 'Anos de Experiência',
    hero_stat_2: 'Alunos Formados',
    hero_stat_3: 'Campeão Mundial',
    
    // Home - Services Preview
    services_preview_badge: 'Os Nossos Serviços',
    services_preview_title: 'Experiências Equestres de Excelência',
    services_preview_subtitle: 'Desde iniciantes a cavaleiros experientes, oferecemos programas personalizados para todas as idades e níveis.',
    service_1_title: 'Aulas Particulares',
    service_1_desc: 'Aulas individuais com monitores experientes ou com o Bi-Campeão Mundial Gilberto Filipe.',
    service_2_title: 'Aulas em Grupo',
    service_2_desc: 'Aulas com até 4 alunos, promovendo aprendizagem colaborativa e socialização.',

    service_4_title: 'Aluguer de Espaço',
    service_4_desc: 'Espaço único para eventos, festas de aniversário e celebrações especiais.',
    services_view_all: 'Ver Todos os Serviços',
    
    // Home - About
    about_badge: 'Sobre Nós',
    about_title: 'Uma Tradição de Excelência Equestre',
    about_p1: 'O Picadeiro Quinta da Horta é mais do que um centro equestre — é um lugar onde a paixão pelos cavalos encontra a excelência no ensino. Localizado na bela região de Alcochete, oferecemos um ambiente natural e tranquilo para a prática da equitação.',
    about_p2: 'Sob a orientação do Bi-Campeão do Mundo Gilberto Filipe, desenvolvemos programas personalizados que respeitam o ritmo de cada aluno, desde iniciantes aos mais experientes.',
    about_feature_1: 'Bi-Campeão Mundial',
    about_feature_1_desc: 'Gilberto Filipe, instrutor principal',
    about_feature_2: 'Segurança Total',
    about_feature_2_desc: 'Protocolos rigorosos de segurança',
    about_feature_3: 'Paixão pelos Cavalos',
    about_feature_3_desc: 'Cuidado e respeito animal',
    about_feature_4: 'Comunidade',
    about_feature_4_desc: 'Ambiente familiar acolhedor',
    about_cta: 'Contacte-nos',
    about_years: 'Anos',
    about_experience: 'de Experiência',
    
    // Home - CTA
    cta_title: 'Pronto para Começar a Sua',
    cta_title_highlight: ' Jornada Equestre?',
    cta_subtitle: 'Dê o primeiro passo para uma experiência única com cavalos. Reserve a sua primeira aula experimental ou entre em contacto para mais informações.',
    cta_book: 'Reservar Aula',
    cta_call: 'Ligar Agora',
    cta_card_1: 'Aula Experimental',
    cta_card_1_desc: 'Experimente uma aula introdutória e descubra o mundo da equitação.',
    cta_card_2: 'Visita às Instalações',
    cta_card_2_desc: 'Agende uma visita para conhecer o nosso espaço e os nossos cavalos.',
    cta_card_3: 'Pacotes Mensais',
    cta_card_3_desc: 'Descubra os nossos planos com condições especiais para alunos regulares.',
    
    // Services
    services_title: 'Os Nossos Serviços',
    services_page_title: 'Os Nossos Serviços',
    services_page_subtitle: 'Programas personalizados para todas as idades e níveis de experiência',
    not_found_services: 'Não encontrou o que procurava?',
    not_found_services_desc: 'Entre em contacto connosco para soluções personalizadas e programas à medida das suas necessidades.',
    talk_to_us: 'Fale Connosco',
    book_now: 'Reservar Agora',
    learn_more: 'Saber Mais',
    from_price: 'Desde',
    
    // Service Descriptions
    service_private_title: 'Aulas Particulares',
    service_private_short: 'Aulas individuais personalizadas',
    service_private_desc: 'Aulas particulares com monitores experientes e com o Bi-Campeão do Mundo de Equitação – Gilberto Filipe. Programa totalmente adaptado ao seu nível e objetivos.',
    service_private_feat_1: 'Instrutor dedicado',
    service_private_feat_2: 'Programa personalizado',
    service_private_feat_3: 'Acompanhamento individual',
    service_private_feat_4: 'Flexibilidade horária',
    
    service_group_title: 'Aulas em Grupo',
    service_group_short: 'Máximo de 4 alunos por aula',
    service_group_desc: 'Aulas em grupo com até 4 alunos, promovendo a aprendizagem colaborativa, socialização e espírito de equipa num ambiente divertido.',
    service_group_feat_1: 'Máximo 4 alunos',
    service_group_feat_2: 'Ambiente social',
    service_group_feat_3: 'Aprendizagem em equipa',
    service_group_feat_4: 'Preço acessível',
    

    service_rental_title: 'Aluguer de Espaço',
    service_rental_short: 'Eventos e festas de aniversário',
    service_rental_desc: 'Espaço único e acolhedor para eventos especiais, festas de aniversário e celebrações. Inclui atividades com cavalos opcionais.',
    service_rental_feat_1: 'Espaço privativo',
    service_rental_feat_2: 'Decoração incluída',
    service_rental_feat_3: 'Atividades opcionais',
    service_rental_feat_4: 'Catering disponível',
    
    service_owners_title: 'Proprietários',
    service_owners_short: 'Reservas para proprietários',
    service_owners_desc: 'Serviço exclusivo para proprietários de cavalos. Permite marcação de horários com prioridade secundária em relação aos alunos regulares.',
    service_owners_feat_1: 'Horários flexíveis',
    service_owners_feat_2: 'Sujeito a disponibilidade',
    service_owners_feat_3: 'Máximo 6 alunos por sessão',
    service_owners_feat_4: 'Prioridade para alunos regulares',
    
    // Bookings
    my_lessons: 'Minhas Aulas',
    new_booking: 'Nova Reserva',
    payments: 'Pagamentos',
    select_service: 'Escolha o Serviço',
    select_plan: 'Escolha o Plano',
    select_date_time: 'Escolha a Data e Hora',
    confirm_booking: 'Confirme a Reserva',
    booking_confirmed: 'Reserva Confirmada!',
    
    // Shop
    shop_title: 'Loja',
    featured_products: 'Produtos em Destaque',
    search_products: 'Pesquisar produtos...',
    sort_by: 'Ordenar por',
    price_low_high: 'Preço: Menor ao Maior',
    price_high_low: 'Preço: Maior ao Menor',
    name_az: 'Nome A-Z',
    no_products_found: 'Nenhum produto encontrado',
    added_to_cart: 'Produto adicionado ao carrinho!',
    all_categories_shop: 'Todos',
    add_to_cart: 'Adicionar ao Carrinho',
    view_cart: 'Ver Carrinho',
    checkout: 'Finalizar Compra',
    
    // Contact
    contact_title: 'Contactos',
    get_in_touch: 'Entre em Contacto',
    contact_subtitle: 'Tem alguma dúvida ou quer saber mais sobre os nossos serviços? Estamos aqui para ajudar!',
    name: 'Nome',
    email: 'Email',
    phone: 'Telefone',
    message: 'Mensagem',
    send_message: 'Enviar Mensagem',
    subject: 'Assunto',
    address: 'Morada',
    opening_hours: 'Horário',
    monday_friday: 'Segunda a Sexta',
    your_name: 'O seu nome',
    your_email: 'O seu email',
    your_phone: 'O seu telefone',
    your_message: 'A sua mensagem',
    message_sent: 'Mensagem enviada!',
    
    // Reviews
    reviews: 'Avaliações',
    write_review: 'Escrever Avaliação',
    rating: 'Classificação',
    review_title: 'Título',
    review_comment: 'Comentário',
    review_placeholder: 'Conte-nos sobre a sua experiência...',
    publish_review: 'Publicar Avaliação',
    sending: 'A enviar...',
    login_to_review: 'Faça login para avaliar',
    fill_all_fields: 'Preencha todos os campos',
    review_sent: 'Avaliação enviada! Aguarde aprovação.',
    verified_purchase: 'Compra verificada',
    
    // Payments
    total_paid: 'Total Pago',
    pending: 'Pendente',
    penalties: 'Penalizações',
    payment_history: 'Histórico de Pagamentos',
    no_payments: 'Sem pagamentos registados',
    monthly_fee: 'Mensalidade',
    due_date: 'Vencimento',
    paid_on: 'Pago em',
    penalty_applied: 'Penalização aplicada',
    payment_rules: 'Regras de Pagamento',
    account_blocked: 'Conta Bloqueada',
    debt_warning: 'A sua conta está bloqueada devido a dívidas superiores a 30€.',
    active_restrictions: 'Restrições ativas',
    no_new_bookings: 'Não pode fazer novas reservas',
    no_classes: 'Não pode participar em aulas',
    no_competitions: 'Não pode participar em provas',
    no_club_representation: 'Não pode representar o clube',
    total_debt: 'Dívida Total',
    pending_payments: 'Pagamentos Pendentes',
    regularize_warning: 'Por favor regularize os seus pagamentos para evitar penalizações.',
    amount_owed: 'Valor em dívida',
    overdue: 'Em Atraso',
    min: 'min',
    max: 'Máx.',
    from: 'Desde',
    booking_confirmation_message: 'A sua reserva foi registada. Enviámos um email de confirmação.',
    
    // Common
    continue: 'Continuar',
    back: 'Voltar',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Apagar',
    edit: 'Editar',
    search: 'Pesquisar',
    loading: 'A carregar...',
    error: 'Erro',
    success: 'Sucesso',
    confirm: 'Confirmar',
    price: 'Preço',
    duration: 'Duração',
    date: 'Data',
    time: 'Hora',
    status: 'Estado',
    
    // Home Hero
    excellence_center: 'Centro Equestre de Excelência',
    world_champion_intro: 'Descubra a arte da equitação com o',
    world_champion_name: 'Bi-Campeão do Mundo Gilberto Filipe',
    hero_description: 'Oferecemos aulas personalizadas e experiências únicas com cavalos num ambiente natural e acolhedor.',
    book_lesson: 'Reservar Aula',
    know_services: 'Conhecer Serviços',
    years_experience: 'Anos de Experiência',
    students_trained: 'Alunos Formados',
    world_champion: 'Campeão Mundial',
    
    // Services Preview
    our_services: 'Os Nossos Serviços',
    equestrian_experiences: 'Experiências Equestres de Excelência',
    services_description: 'Desde iniciantes a cavaleiros experientes, oferecemos programas personalizados para todas as idades e níveis.',
    private_lessons: 'Aulas Particulares',
    private_lessons_desc: 'Aulas individuais com monitores experientes ou com o Bi-Campeão Mundial Gilberto Filipe.',
    group_lessons: 'Aulas em Grupo',
    group_lessons_desc: 'Aulas com até 4 alunos, promovendo aprendizagem colaborativa e socialização.',

    space_rental: 'Aluguer de Espaço',
    space_rental_desc: 'Espaço único para eventos, festas de aniversário e celebrações especiais.',
    view_all_services: 'Ver Todos os Serviços',
    
    // About
    about_us: 'Sobre Nós',
    excellence_tradition: 'Uma Tradição de Excelência Equestre',
    about_description_1: 'O Picadeiro Quinta da Horta é mais do que um centro equestre — é um lugar onde a paixão pelos cavalos encontra a excelência no ensino. Localizado na bela região de Alcochete, oferecemos um ambiente natural e tranquilo para a prática da equitação.',
    about_description_2: 'desenvolvemos programas personalizados que respeitam o ritmo de cada aluno, desde iniciantes aos mais experientes.',
    contact_us: 'Contacte-nos',
    
    // CTA
    ready_to_start: 'Pronto para Começar a Sua',
    equestrian_journey: 'Jornada Equestre?',
    cta_description: 'Dê o primeiro passo para uma experiência única com cavalos. Reserve a sua primeira aula experimental ou entre em contacto para mais informações.',
    call_now: 'Ligar Agora',
    trial_lesson: 'Aula Experimental',
    trial_lesson_desc: 'Experimente uma aula introdutória e descubra o mundo da equitação.',
    visit_facilities: 'Visita às Instalações',
    visit_facilities_desc: 'Agende uma visita para conhecer o nosso espaço e os nossos cavalos.',
    monthly_packages: 'Pacotes Mensais',
    monthly_packages_desc: 'Descubra os nossos planos com condições especiais para alunos regulares.',
    
    // Bookings
    bookings_area: 'Área de Reservas',
    bookings_login_message: 'Faça login para gerir as suas reservas, confirmar presença e consultar pagamentos.',
    login_or_register: 'Entrar ou Registar',
    hello: 'Olá',
    manage_bookings_subtitle: 'Gerir as suas aulas, confirmar presença e consultar pagamentos',
    my_classes: 'Minhas Aulas',
    new_booking: 'Nova Reserva',
    payments: 'Pagamentos',
    filters: 'Filtros',
    
    // Gallery
    our_gallery: 'A Nossa Galeria',
    gallery_title: 'Momentos Inesquecíveis',
    gallery_subtitle: 'Descubra os melhores momentos do nosso centro equestre através de imagens',
    all_categories: 'Todas',
    classes: 'Aulas',
    events: 'Eventos',
    horses: 'Cavalos',
    facilities: 'Instalações',
    competitions: 'Competições',
    others: 'Outros',
    no_images: 'Nenhuma imagem encontrada',

    // Footer
    quick_links: 'Links Rápidos',
    footer_description: 'Centro equestre de excelência em Alcochete, oferecendo aulas de equitação e experiências únicas com cavalos.',
    
    // Cart & Checkout
    cart_title: 'Carrinho de Compras',
    your_cart: 'O Seu Carrinho',
    cart_empty: 'O seu carrinho está vazio',
    continue_shopping: 'Continuar a Comprar',
    quantity: 'Quantidade',
    subtotal: 'Subtotal',
    discount: 'Desconto',
    shipping: 'Envio',
    total: 'Total',
    apply_coupon: 'Aplicar Cupão',
    coupon_code: 'Código do Cupão',
    apply: 'Aplicar',
    proceed_checkout: 'Finalizar Compra',
    checkout_title: 'Finalizar Compra',
    shipping_address: 'Morada de Envio',
    street: 'Rua',
    city: 'Cidade',
    postal_code: 'Código Postal',
    country: 'País',
    place_order: 'Fazer Pedido',
    order_success: 'Pedido Realizado!',
    order_confirmation: 'O seu pedido foi recebido e será processado em breve.',
    order_number: 'Número do Pedido',
    back_to_shop: 'Voltar à Loja',
    remove: 'Remover',
    removed_from_cart: 'Produto removido do carrinho',
    products: 'Produtos',
    order_summary: 'Resumo',
    coupon_applied: 'Cupão',
    applied: 'aplicado',
    free: 'Grátis',
    free_shipping_note: 'Envio grátis para encomendas superiores a 50€',
    processing: 'A processar...',
    back_to_cart: 'Voltar ao Carrinho',
  },
  
  en: {
    // Navigation
    nav_home: 'Home',
    nav_services: 'Services',
    nav_gallery: 'Gallery',
    nav_shop: 'Shop',
    nav_bookings: 'Bookings',
    nav_contact: 'Contact',
    
    // Auth
    login: 'Login',
    logout: 'Logout',
    my_account: 'My Account',
    
    // Home - Hero
    hero_badge: 'Equestrian Center of Excellence',
    hero_title: 'Picadeiro',
    hero_title_highlight: 'Quinta da Horta',
    hero_description: 'Discover the art of horse riding with World Champion Gilberto Filipe. We offer personalized lessons and unique experiences with horses in a natural and welcoming environment.',
    hero_cta_primary: 'Book Lesson',
    hero_cta_secondary: 'Discover Services',
    hero_stat_1: 'Years of Experience',
    hero_stat_2: 'Trained Students',
    hero_stat_3: 'World Champion',
    
    // Home - Services Preview
    services_preview_badge: 'Our Services',
    services_preview_title: 'Excellent Equestrian Experiences',
    services_preview_subtitle: 'From beginners to experienced riders, we offer personalized programs for all ages and levels.',
    service_1_title: 'Private Lessons',
    service_1_desc: 'Individual lessons with experienced instructors or World Champion Gilberto Filipe.',
    service_2_title: 'Group Lessons',
    service_2_desc: 'Lessons with up to 4 students, promoting collaborative learning and socialization.',
    service_3_title: 'Hippotherapy',
    service_3_desc: 'Horse-assisted therapy for physical, emotional and cognitive development.',
    service_4_title: 'Space Rental',
    service_4_desc: 'Unique space for events, birthday parties and special celebrations.',
    services_view_all: 'View All Services',
    
    // Home - About
    about_badge: 'About Us',
    about_title: 'A Tradition of Equestrian Excellence',
    about_p1: 'Picadeiro Quinta da Horta is more than an equestrian center — it\'s a place where passion for horses meets excellence in teaching. Located in the beautiful region of Alcochete, we offer a natural and peaceful environment for horse riding.',
    about_p2: 'Under the guidance of World Champion Gilberto Filipe, we develop personalized programs that respect each student\'s pace, from beginners to the most experienced.',
    about_feature_1: 'World Champion',
    about_feature_1_desc: 'Gilberto Filipe, lead instructor',
    about_feature_2: 'Total Safety',
    about_feature_2_desc: 'Rigorous safety protocols',
    about_feature_3: 'Passion for Horses',
    about_feature_3_desc: 'Animal care and respect',
    about_feature_4: 'Community',
    about_feature_4_desc: 'Welcoming family environment',
    about_cta: 'Contact Us',
    about_years: 'Years',
    about_experience: 'of Experience',
    
    // Home - CTA
    cta_title: 'Ready to Start Your',
    cta_title_highlight: ' Equestrian Journey?',
    cta_subtitle: 'Take the first step towards a unique experience with horses. Book your first trial lesson or contact us for more information.',
    cta_book: 'Book Lesson',
    cta_call: 'Call Now',
    cta_card_1: 'Trial Lesson',
    cta_card_1_desc: 'Try an introductory lesson and discover the world of horse riding.',
    cta_card_2: 'Facility Visit',
    cta_card_2_desc: 'Schedule a visit to see our space and meet our horses.',
    cta_card_3: 'Monthly Packages',
    cta_card_3_desc: 'Discover our plans with special conditions for regular students.',
    
    // Services
    services_title: 'Our Services',
    services_page_title: 'Services',
    services_page_subtitle: 'Personalized programs for all ages and experience levels',
    not_found_services: 'Didn\'t find what you were looking for?',
    not_found_services_desc: 'Contact us for personalized solutions and programs tailored to your needs.',
    talk_to_us: 'Talk to Us',
    book_now: 'Book Now',
    learn_more: 'Learn More',
    from_price: 'From',
    
    // Service Descriptions
    service_private_title: 'Private Lessons',
    service_private_short: 'Personalized individual lessons',
    service_private_desc: 'Private lessons with experienced instructors and 2x World Champion Gilberto Filipe. Program fully adapted to your level and goals.',
    service_private_feat_1: 'Dedicated instructor',
    service_private_feat_2: 'Personalized program',
    service_private_feat_3: 'Individual monitoring',
    service_private_feat_4: 'Schedule flexibility',
    
    service_group_title: 'Group Lessons',
    service_group_short: 'Maximum 4 students per class',
    service_group_desc: 'Group lessons with up to 4 students, promoting collaborative learning, socialization and team spirit in a fun environment.',
    service_group_feat_1: 'Maximum 4 students',
    service_group_feat_2: 'Social environment',
    service_group_feat_3: 'Team learning',
    service_group_feat_4: 'Affordable price',
    

    service_rental_title: 'Space Rental',
    service_rental_short: 'Events and birthday parties',
    service_rental_desc: 'Unique and welcoming space for special events, birthday parties and celebrations. Optional horse activities included.',
    service_rental_feat_1: 'Private space',
    service_rental_feat_2: 'Decoration included',
    service_rental_feat_3: 'Optional activities',
    service_rental_feat_4: 'Catering available',
    
    service_owners_title: 'Owners',
    service_owners_short: 'Bookings for horse owners',
    service_owners_desc: 'Exclusive service for horse owners. Allows time slot booking with secondary priority relative to regular students.',
    service_owners_feat_1: 'Flexible schedules',
    service_owners_feat_2: 'Subject to availability',
    service_owners_feat_3: 'Maximum 6 students per session',
    service_owners_feat_4: 'Priority for regular students',
    
    // Bookings
    my_lessons: 'My Lessons',
    new_booking: 'New Booking',
    payments: 'Payments',
    select_service: 'Select Service',
    select_plan: 'Select Plan',
    select_date_time: 'Select Date & Time',
    confirm_booking: 'Confirm Booking',
    booking_confirmed: 'Booking Confirmed!',
    
    // Shop
    shop_title: 'Shop',
    featured_products: 'Featured Products',
    search_products: 'Search products...',
    sort_by: 'Sort by',
    price_low_high: 'Price: Low to High',
    price_high_low: 'Price: High to Low',
    name_az: 'Name A-Z',
    no_products_found: 'No products found',
    added_to_cart: 'Product added to cart!',
    all_categories_shop: 'All',
    add_to_cart: 'Add to Cart',
    view_cart: 'View Cart',
    checkout: 'Checkout',
    
    // Contact
    contact_title: 'Contact',
    get_in_touch: 'Get in Touch',
    contact_subtitle: 'Have a question or want to know more about our services? We\'re here to help!',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    message: 'Message',
    send_message: 'Send Message',
    subject: 'Subject',
    address: 'Address',
    opening_hours: 'Opening Hours',
    monday_friday: 'Monday to Friday',
    your_name: 'Your name',
    your_email: 'Your email',
    your_phone: 'Your phone',
    your_message: 'Your message',
    message_sent: 'Message sent!',
    
    // Reviews
    reviews: 'Reviews',
    write_review: 'Write Review',
    rating: 'Rating',
    review_title: 'Title',
    review_comment: 'Comment',
    review_placeholder: 'Tell us about your experience...',
    publish_review: 'Publish Review',
    sending: 'Sending...',
    login_to_review: 'Login to review',
    fill_all_fields: 'Fill all fields',
    review_sent: 'Review submitted! Awaiting approval.',
    verified_purchase: 'Verified purchase',
    
    // Payments
    total_paid: 'Total Paid',
    pending: 'Pending',
    penalties: 'Penalties',
    payment_history: 'Payment History',
    no_payments: 'No payments recorded',
    monthly_fee: 'Monthly Fee',
    due_date: 'Due Date',
    paid_on: 'Paid on',
    penalty_applied: 'Penalty applied',
    payment_rules: 'Payment Rules',
    account_blocked: 'Account Blocked',
    debt_warning: 'Your account is blocked due to debts over 30€.',
    active_restrictions: 'Active restrictions',
    no_new_bookings: 'Cannot make new bookings',
    no_classes: 'Cannot participate in classes',
    no_competitions: 'Cannot participate in competitions',
    no_club_representation: 'Cannot represent the club',
    total_debt: 'Total Debt',
    pending_payments: 'Pending Payments',
    regularize_warning: 'Please settle your payments to avoid penalties.',
    amount_owed: 'Amount owed',
    overdue: 'Overdue',
    min: 'min',
    max: 'Max.',
    from: 'From',
    booking_confirmation_message: 'Your booking has been registered. We have sent you a confirmation email.',
    
    // Common
    continue: 'Continue',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    confirm: 'Confirm',
    price: 'Price',
    duration: 'Duration',
    date: 'Date',
    time: 'Time',
    status: 'Status',
    
    // Home Hero
    excellence_center: 'Equestrian Centre of Excellence',
    world_champion_intro: 'Discover the art of horse riding with',
    world_champion_name: '2x World Champion Gilberto Filipe',
    hero_description: 'We offer personalized lessons, hippotherapy and unique experiences with horses in a natural and welcoming environment.',
    book_lesson: 'Book Lesson',
    know_services: 'Discover Services',
    years_experience: 'Years of Experience',
    students_trained: 'Trained Students',
    world_champion: 'World Champion',
    
    // Services Preview
    our_services: 'Our Services',
    equestrian_experiences: 'Excellence Equestrian Experiences',
    services_description: 'From beginners to experienced riders, we offer personalized programs for all ages and levels.',
    private_lessons: 'Private Lessons',
    private_lessons_desc: 'Individual lessons with experienced instructors or with 2x World Champion Gilberto Filipe.',
    group_lessons: 'Group Lessons',
    group_lessons_desc: 'Classes with up to 4 students, promoting collaborative learning and socialization.',

    space_rental: 'Space Rental',
    space_rental_desc: 'Unique space for events, birthday parties and special celebrations.',
    view_all_services: 'View All Services',
    
    // About
    about_us: 'About Us',
    excellence_tradition: 'A Tradition of Equestrian Excellence',
    about_description_1: 'Picadeiro Quinta da Horta is more than an equestrian center — it is a place where passion for horses meets excellence in teaching. Located in the beautiful region of Alcochete, we offer a natural and peaceful environment for horse riding.',
    about_description_2: 'we develop personalized programs that respect the pace of each student, from beginners to the most experienced.',
    contact_us: 'Contact Us',
    
    // CTA
    ready_to_start: 'Ready to Start Your',
    equestrian_journey: 'Equestrian Journey?',
    cta_description: 'Take the first step towards a unique experience with horses. Book your first trial lesson or get in touch for more information.',
    call_now: 'Call Now',
    trial_lesson: 'Trial Lesson',
    trial_lesson_desc: 'Try an introductory lesson and discover the world of horse riding.',
    visit_facilities: 'Visit Facilities',
    visit_facilities_desc: 'Schedule a visit to see our space and our horses.',
    monthly_packages: 'Monthly Packages',
    monthly_packages_desc: 'Discover our plans with special conditions for regular students.',
    
    // Bookings
    bookings_area: 'Bookings Area',
    bookings_login_message: 'Login to manage your bookings, confirm attendance and check payments.',
    login_or_register: 'Login or Register',
    hello: 'Hello',
    manage_bookings_subtitle: 'Manage your classes, confirm attendance and check payments',
    my_classes: 'My Classes',
    new_booking: 'New Booking',
    payments: 'Payments',
    filters: 'Filters',
    
    // Gallery
    our_gallery: 'Our Gallery',
    gallery_title: 'Unforgettable Moments',
    gallery_subtitle: 'Discover the best moments of our equestrian center through images',
    all_categories: 'All',
    classes: 'Classes',
    events: 'Events',
    horses: 'Horses',
    facilities: 'Facilities',
    competitions: 'Competitions',
    others: 'Others',
    no_images: 'No images found',

    // Footer
    quick_links: 'Quick Links',
    footer_description: 'Equestrian center of excellence in Alcochete, offering riding lessons and unique experiences with horses.',
    
    // Cart & Checkout
    cart_title: 'Shopping Cart',
    your_cart: 'Your Cart',
    cart_empty: 'Your cart is empty',
    continue_shopping: 'Continue Shopping',
    quantity: 'Quantity',
    subtotal: 'Subtotal',
    discount: 'Discount',
    shipping: 'Shipping',
    total: 'Total',
    apply_coupon: 'Apply Coupon',
    coupon_code: 'Coupon Code',
    apply: 'Apply',
    proceed_checkout: 'Proceed to Checkout',
    checkout_title: 'Checkout',
    shipping_address: 'Shipping Address',
    street: 'Street',
    city: 'City',
    postal_code: 'Postal Code',
    country: 'Country',
    place_order: 'Place Order',
    order_success: 'Order Placed!',
    order_confirmation: 'Your order has been received and will be processed shortly.',
    order_number: 'Order Number',
    back_to_shop: 'Back to Shop',
    remove: 'Remove',
    removed_from_cart: 'Product removed from cart',
    products: 'Products',
    order_summary: 'Summary',
    coupon_applied: 'Coupon',
    applied: 'applied',
    free: 'Free',
    free_shipping_note: 'Free shipping for orders over 50€',
    processing: 'Processing...',
    back_to_cart: 'Back to Cart',
  },
  
  es: {
    // Navigation
    nav_home: 'Inicio',
    nav_services: 'Servicios',
    nav_gallery: 'Galería',
    nav_shop: 'Tienda',
    nav_bookings: 'Reservas',
    nav_contact: 'Contacto',
    
    // Auth
    login: 'Iniciar Sesión',
    logout: 'Cerrar Sesión',
    my_account: 'Mi Cuenta',
    
    // Home - Hero
    hero_badge: 'Centro Ecuestre de Excelencia',
    hero_title: 'Picadeiro',
    hero_title_highlight: 'Quinta da Horta',
    hero_description: 'Descubre el arte de la equitación con el Bicampeón del Mundo Gilberto Filipe. Ofrecemos clases personalizadas y experiencias únicas con caballos en un ambiente natural y acogedor.',
    hero_cta_primary: 'Reservar Clase',
    hero_cta_secondary: 'Conocer Servicios',
    hero_stat_1: 'Años de Experiencia',
    hero_stat_2: 'Alumnos Formados',
    hero_stat_3: 'Campeón Mundial',
    
    // Home - Services Preview
    services_preview_badge: 'Nuestros Servicios',
    services_preview_title: 'Experiencias Ecuestres de Excelencia',
    services_preview_subtitle: 'Desde principiantes a jinetes experimentados, ofrecemos programas personalizados para todas las edades y niveles.',
    service_1_title: 'Clases Particulares',
    service_1_desc: 'Clases individuales con instructores experimentados o con el Bicampeón Mundial Gilberto Filipe.',
    service_2_title: 'Clases en Grupo',
    service_2_desc: 'Clases con hasta 4 alumnos, promoviendo el aprendizaje colaborativo y la socialización.',
    service_3_title: 'Hipoterapia',
    service_3_desc: 'Terapia asistida por caballos para el desarrollo físico, emocional y cognitivo.',
    service_4_title: 'Alquiler de Espacio',
    service_4_desc: 'Espacio único para eventos, fiestas de cumpleaños y celebraciones especiales.',
    services_view_all: 'Ver Todos los Servicios',
    
    // Home - About
    about_badge: 'Sobre Nosotros',
    about_title: 'Una Tradición de Excelencia Ecuestre',
    about_p1: 'Picadeiro Quinta da Horta es más que un centro ecuestre — es un lugar donde la pasión por los caballos se encuentra con la excelencia en la enseñanza. Ubicado en la hermosa región de Alcochete, ofrecemos un ambiente natural y tranquilo para la práctica de la equitación.',
    about_p2: 'Bajo la dirección del Bicampeón del Mundo Gilberto Filipe, desarrollamos programas personalizados que respetan el ritmo de cada alumno, desde principiantes hasta los más experimentados.',
    about_feature_1: 'Bicampeón Mundial',
    about_feature_1_desc: 'Gilberto Filipe, instructor principal',
    about_feature_2: 'Seguridad Total',
    about_feature_2_desc: 'Protocolos rigurosos de seguridad',
    about_feature_3: 'Pasión por los Caballos',
    about_feature_3_desc: 'Cuidado y respeto animal',
    about_feature_4: 'Comunidad',
    about_feature_4_desc: 'Ambiente familiar acogedor',
    about_cta: 'Contáctenos',
    about_years: 'Años',
    about_experience: 'de Experiencia',
    
    // Home - CTA
    cta_title: 'Listo para Comenzar Tu',
    cta_title_highlight: ' Viaje Ecuestre?',
    cta_subtitle: 'Da el primer paso hacia una experiencia única con caballos. Reserva tu primera clase de prueba o contáctanos para más información.',
    cta_book: 'Reservar Clase',
    cta_call: 'Llamar Ahora',
    cta_card_1: 'Clase de Prueba',
    cta_card_1_desc: 'Prueba una clase introductoria y descubre el mundo de la equitación.',
    cta_card_2: 'Visita a las Instalaciones',
    cta_card_2_desc: 'Agenda una visita para conocer nuestro espacio y nuestros caballos.',
    cta_card_3: 'Paquetes Mensuales',
    cta_card_3_desc: 'Descubre nuestros planes con condiciones especiales para alumnos regulares.',
    
    // Services
    services_title: 'Nuestros Servicios',
    services_page_title: 'Servicios',
    services_page_subtitle: 'Programas personalizados para todas las edades y niveles de experiencia',
    not_found_services: '¿No encontraste lo que buscabas?',
    not_found_services_desc: 'Contáctenos para soluciones personalizadas y programas adaptados a sus necesidades.',
    talk_to_us: 'Hable con Nosotros',
    book_now: 'Reservar Ahora',
    learn_more: 'Saber Más',
    from_price: 'Desde',
    
    // Service Descriptions
    service_private_title: 'Clases Particulares',
    service_private_short: 'Clases individuales personalizadas',
    service_private_desc: 'Clases particulares con instructores experimentados y con el Bicampeón Mundial de Equitación – Gilberto Filipe. Programa totalmente adaptado a tu nivel y objetivos.',
    service_private_feat_1: 'Instructor dedicado',
    service_private_feat_2: 'Programa personalizado',
    service_private_feat_3: 'Seguimiento individual',
    service_private_feat_4: 'Flexibilidad horaria',
    
    service_group_title: 'Clases en Grupo',
    service_group_short: 'Máximo 4 alumnos por clase',
    service_group_desc: 'Clases en grupo con hasta 4 alumnos, promoviendo el aprendizaje colaborativo, la socialización y el espíritu de equipo en un ambiente divertido.',
    service_group_feat_1: 'Máximo 4 alumnos',
    service_group_feat_2: 'Ambiente social',
    service_group_feat_3: 'Aprendizaje en equipo',
    service_group_feat_4: 'Precio accesible',
    

    service_rental_title: 'Alquiler de Espacio',
    service_rental_short: 'Eventos y fiestas de cumpleaños',
    service_rental_desc: 'Espacio único y acogedor para eventos especiales, fiestas de cumpleaños y celebraciones. Incluye actividades opcionales con caballos.',
    service_rental_feat_1: 'Espacio privado',
    service_rental_feat_2: 'Decoración incluida',
    service_rental_feat_3: 'Actividades opcionales',
    service_rental_feat_4: 'Catering disponible',
    
    service_owners_title: 'Propietarios',
    service_owners_short: 'Reservas para propietarios',
    service_owners_desc: 'Servicio exclusivo para propietarios de caballos. Permite reserva de horarios con prioridad secundaria respecto a los alumnos regulares.',
    service_owners_feat_1: 'Horarios flexibles',
    service_owners_feat_2: 'Sujeto a disponibilidad',
    service_owners_feat_3: 'Máximo 6 alumnos por sesión',
    service_owners_feat_4: 'Prioridad para alumnos regulares',
    
    // Bookings
    my_lessons: 'Mis Clases',
    new_booking: 'Nueva Reserva',
    payments: 'Pagos',
    select_service: 'Seleccionar Servicio',
    select_plan: 'Seleccionar Plan',
    select_date_time: 'Seleccionar Fecha y Hora',
    confirm_booking: 'Confirmar Reserva',
    booking_confirmed: '¡Reserva Confirmada!',
    
    // Shop
    shop_title: 'Tienda',
    featured_products: 'Productos Destacados',
    search_products: 'Buscar productos...',
    sort_by: 'Ordenar por',
    price_low_high: 'Precio: Menor a Mayor',
    price_high_low: 'Precio: Mayor a Menor',
    name_az: 'Nombre A-Z',
    no_products_found: 'No se encontraron productos',
    added_to_cart: '¡Producto añadido al carrito!',
    all_categories_shop: 'Todos',
    add_to_cart: 'Añadir al Carrito',
    view_cart: 'Ver Carrito',
    checkout: 'Finalizar Compra',
    
    // Contact
    contact_title: 'Contacto',
    get_in_touch: 'Póngase en Contacto',
    contact_subtitle: '¿Tiene alguna pregunta o quiere saber más sobre nuestros servicios? ¡Estamos aquí para ayudar!',
    name: 'Nombre',
    email: 'Correo',
    phone: 'Teléfono',
    message: 'Mensaje',
    send_message: 'Enviar Mensaje',
    subject: 'Asunto',
    address: 'Dirección',
    opening_hours: 'Horario',
    monday_friday: 'Lunes a Viernes',
    your_name: 'Su nombre',
    your_email: 'Su correo',
    your_phone: 'Su teléfono',
    your_message: 'Su mensaje',
    message_sent: '¡Mensaje enviado!',
    
    // Reviews
    reviews: 'Reseñas',
    write_review: 'Escribir Reseña',
    rating: 'Clasificación',
    review_title: 'Título',
    review_comment: 'Comentario',
    review_placeholder: 'Cuéntenos sobre su experiencia...',
    publish_review: 'Publicar Reseña',
    sending: 'Enviando...',
    login_to_review: 'Inicie sesión para reseñar',
    fill_all_fields: 'Complete todos los campos',
    review_sent: '¡Reseña enviada! Esperando aprobación.',
    verified_purchase: 'Compra verificada',
    
    // Payments
    total_paid: 'Total Pagado',
    pending: 'Pendiente',
    penalties: 'Penalizaciones',
    payment_history: 'Historial de Pagos',
    no_payments: 'Sin pagos registrados',
    monthly_fee: 'Mensualidad',
    due_date: 'Vencimiento',
    paid_on: 'Pagado el',
    penalty_applied: 'Penalización aplicada',
    payment_rules: 'Reglas de Pago',
    account_blocked: 'Cuenta Bloqueada',
    debt_warning: 'Su cuenta está bloqueada debido a deudas superiores a 30€.',
    active_restrictions: 'Restricciones activas',
    no_new_bookings: 'No puede hacer nuevas reservas',
    no_classes: 'No puede participar en clases',
    no_competitions: 'No puede participar en competiciones',
    no_club_representation: 'No puede representar al club',
    total_debt: 'Deuda Total',
    pending_payments: 'Pagos Pendientes',
    regularize_warning: 'Por favor regularice sus pagos para evitar penalizaciones.',
    amount_owed: 'Importe adeudado',
    overdue: 'Atrasado',
    min: 'min',
    max: 'Máx.',
    from: 'Desde',
    booking_confirmation_message: 'Su reserva ha sido registrada. Le hemos enviado un correo de confirmación.',
    
    // Common
    continue: 'Continuar',
    back: 'Volver',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    search: 'Buscar',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    confirm: 'Confirmar',
    price: 'Precio',
    duration: 'Duración',
    date: 'Fecha',
    time: 'Hora',
    status: 'Estado',
    
    // Home Hero
    excellence_center: 'Centro Ecuestre de Excelencia',
    world_champion_intro: 'Descubre el arte de la equitación con',
    world_champion_name: 'Bicampeón Mundial Gilberto Filipe',
    hero_description: 'Ofrecemos clases personalizadas y experiencias únicas con caballos en un ambiente natural y acogedor.',
    book_lesson: 'Reservar Clase',
    know_services: 'Conocer Servicios',
    years_experience: 'Años de Experiencia',
    students_trained: 'Alumnos Formados',
    world_champion: 'Campeón Mundial',
    
    // Services Preview
    our_services: 'Nuestros Servicios',
    equestrian_experiences: 'Experiencias Ecuestres de Excelencia',
    services_description: 'Desde principiantes hasta jinetes experimentados, ofrecemos programas personalizados para todas las edades y niveles.',
    private_lessons: 'Clases Particulares',
    private_lessons_desc: 'Clases individuales con monitores experimentados o con el Bicampeón Mundial Gilberto Filipe.',
    group_lessons: 'Clases en Grupo',
    group_lessons_desc: 'Clases con hasta 4 alumnos, promoviendo el aprendizaje colaborativo y la socialización.',

    space_rental: 'Alquiler de Espacio',
    space_rental_desc: 'Espacio único para eventos, fiestas de cumpleaños y celebraciones especiales.',
    view_all_services: 'Ver Todos los Servicios',
    
    // About
    about_us: 'Sobre Nosotros',
    excellence_tradition: 'Una Tradición de Excelencia Ecuestre',
    about_description_1: 'El Picadeiro Quinta da Horta es más que un centro ecuestre — es un lugar donde la pasión por los caballos encuentra la excelencia en la enseñanza. Ubicado en la hermosa región de Alcochete, ofrecemos un ambiente natural y tranquilo para la práctica de la equitación.',
    about_description_2: 'desarrollamos programas personalizados que respetan el ritmo de cada alumno, desde principiantes hasta los más experimentados.',
    contact_us: 'Contáctenos',
    
    // CTA
    ready_to_start: 'Listo para Comenzar Tu',
    equestrian_journey: 'Viaje Ecuestre?',
    cta_description: 'Da el primer paso hacia una experiencia única con caballos. Reserva tu primera clase de prueba o ponte en contacto para más información.',
    call_now: 'Llamar Ahora',
    trial_lesson: 'Clase de Prueba',
    trial_lesson_desc: 'Prueba una clase introductoria y descubre el mundo de la equitación.',
    visit_facilities: 'Visita a las Instalaciones',
    visit_facilities_desc: 'Agenda una visita para conocer nuestro espacio y nuestros caballos.',
    monthly_packages: 'Paquetes Mensuales',
    monthly_packages_desc: 'Descubre nuestros planes con condiciones especiales para alumnos regulares.',
    
    // Bookings
    bookings_area: 'Área de Reservas',
    bookings_login_message: 'Inicia sesión para gestionar tus reservas, confirmar asistencia y consultar pagos.',
    login_or_register: 'Iniciar Sesión o Registrarse',
    hello: 'Hola',
    manage_bookings_subtitle: 'Gestionar tus clases, confirmar asistencia y consultar pagos',
    my_classes: 'Mis Clases',
    new_booking: 'Nueva Reserva',
    payments: 'Pagos',
    filters: 'Filtros',
    
    // Gallery
    our_gallery: 'Nuestra Galería',
    gallery_title: 'Momentos Inolvidables',
    gallery_subtitle: 'Descubre los mejores momentos de nuestro centro ecuestre a través de imágenes',
    all_categories: 'Todas',
    classes: 'Clases',
    events: 'Eventos',
    horses: 'Caballos',
    facilities: 'Instalaciones',
    competitions: 'Competiciones',
    others: 'Otros',
    no_images: 'No se encontraron imágenes',

    // Footer
    quick_links: 'Enlaces Rápidos',
    footer_description: 'Centro ecuestre de excelencia en Alcochete, ofreciendo clases de equitación y experiencias únicas con caballos.',
    
    // Cart & Checkout
    cart_title: 'Carrito de Compras',
    your_cart: 'Tu Carrito',
    cart_empty: 'Tu carrito está vacío',
    continue_shopping: 'Seguir Comprando',
    quantity: 'Cantidad',
    subtotal: 'Subtotal',
    discount: 'Descuento',
    shipping: 'Envío',
    total: 'Total',
    apply_coupon: 'Aplicar Cupón',
    coupon_code: 'Código del Cupón',
    apply: 'Aplicar',
    proceed_checkout: 'Finalizar Compra',
    checkout_title: 'Finalizar Compra',
    shipping_address: 'Dirección de Envío',
    street: 'Calle',
    city: 'Ciudad',
    postal_code: 'Código Postal',
    country: 'País',
    place_order: 'Realizar Pedido',
    order_success: '¡Pedido Realizado!',
    order_confirmation: 'Tu pedido ha sido recibido y será procesado pronto.',
    order_number: 'Número de Pedido',
    back_to_shop: 'Volver a la Tienda',
    remove: 'Eliminar',
    removed_from_cart: 'Producto eliminado del carrito',
    products: 'Productos',
    order_summary: 'Resumen',
    coupon_applied: 'Cupón',
    applied: 'aplicado',
    free: 'Gratis',
    free_shipping_note: 'Envío gratis para pedidos superiores a 50€',
    processing: 'Procesando...',
    back_to_cart: 'Volver al Carrito',
  },
  
  fr: {
    // Navigation
    nav_home: 'Accueil',
    nav_services: 'Services',
    nav_gallery: 'Galerie',
    nav_shop: 'Boutique',
    nav_bookings: 'Réservations',
    nav_contact: 'Contact',
    
    // Auth
    login: 'Connexion',
    logout: 'Déconnexion',
    my_account: 'Mon Compte',
    
    // Home - Hero
    hero_badge: 'Centre Équestre d\'Excellence',
    hero_title: 'Picadeiro',
    hero_title_highlight: 'Quinta da Horta',
    hero_description: 'Découvrez l\'art de l\'équitation avec le double Champion du Monde Gilberto Filipe. Nous proposons des cours personnalisés et des expériences uniques avec les chevaux dans un environnement naturel et accueillant.',
    hero_cta_primary: 'Réserver un Cours',
    hero_cta_secondary: 'Découvrir les Services',
    hero_stat_1: 'Ans d\'Expérience',
    hero_stat_2: 'Élèves Formés',
    hero_stat_3: 'Champion du Monde',
    
    // Home - Services Preview
    services_preview_badge: 'Nos Services',
    services_preview_title: 'Expériences Équestres d\'Excellence',
    services_preview_subtitle: 'Des débutants aux cavaliers expérimentés, nous proposons des programmes personnalisés pour tous les âges et niveaux.',
    service_1_title: 'Cours Particuliers',
    service_1_desc: 'Cours individuels avec des instructeurs expérimentés ou avec le double Champion du Monde Gilberto Filipe.',
    service_2_title: 'Cours en Groupe',
    service_2_desc: 'Cours avec jusqu\'à 4 élèves, favorisant l\'apprentissage collaboratif et la socialisation.',
    service_3_title: 'Hippothérapie',
    service_3_desc: 'Thérapie assistée par les chevaux pour le développement physique, émotionnel et cognitif.',
    service_4_title: 'Location d\'Espace',
    service_4_desc: 'Espace unique pour événements, fêtes d\'anniversaire et célébrations spéciales.',
    services_view_all: 'Voir Tous les Services',
    
    // Home - About
    about_badge: 'À Propos',
    about_title: 'Une Tradition d\'Excellence Équestre',
    about_p1: 'Picadeiro Quinta da Horta est plus qu\'un centre équestre — c\'est un lieu où la passion des chevaux rencontre l\'excellence dans l\'enseignement. Situé dans la belle région d\'Alcochete, nous offrons un environnement naturel et paisible pour la pratique de l\'équitation.',
    about_p2: 'Sous la direction du double Champion du Monde Gilberto Filipe, nous développons des programmes personnalisés qui respectent le rythme de chaque élève, des débutants aux plus expérimentés.',
    about_feature_1: 'Double Champion du Monde',
    about_feature_1_desc: 'Gilberto Filipe, instructeur principal',
    about_feature_2: 'Sécurité Totale',
    about_feature_2_desc: 'Protocoles de sécurité rigoureux',
    about_feature_3: 'Passion pour les Chevaux',
    about_feature_3_desc: 'Soins et respect des animaux',
    about_feature_4: 'Communauté',
    about_feature_4_desc: 'Environnement familial accueillant',
    about_cta: 'Contactez-nous',
    about_years: 'Ans',
    about_experience: 'd\'Expérience',
    
    // Home - CTA
    cta_title: 'Prêt à Commencer Votre',
    cta_title_highlight: ' Voyage Équestre?',
    cta_subtitle: 'Faites le premier pas vers une expérience unique avec les chevaux. Réservez votre premier cours d\'essai ou contactez-nous pour plus d\'informations.',
    cta_book: 'Réserver un Cours',
    cta_call: 'Appeler Maintenant',
    cta_card_1: 'Cours d\'Essai',
    cta_card_1_desc: 'Essayez un cours d\'initiation et découvrez le monde de l\'équitation.',
    cta_card_2: 'Visite des Installations',
    cta_card_2_desc: 'Planifiez une visite pour découvrir notre espace et rencontrer nos chevaux.',
    cta_card_3: 'Forfaits Mensuels',
    cta_card_3_desc: 'Découvrez nos plans avec des conditions spéciales pour les élèves réguliers.',
    
    // Services
    services_title: 'Nos Services',
    services_page_title: 'Services',
    services_page_subtitle: 'Programmes personnalisés pour tous les âges et niveaux d\'expérience',
    not_found_services: 'Vous n\'avez pas trouvé ce que vous cherchiez?',
    not_found_services_desc: 'Contactez-nous pour des solutions personnalisées et des programmes adaptés à vos besoins.',
    talk_to_us: 'Parlez-nous',
    book_now: 'Réserver Maintenant',
    learn_more: 'En Savoir Plus',
    from_price: 'À partir de',
    
    // Service Descriptions
    service_private_title: 'Cours Particuliers',
    service_private_short: 'Cours individuels personnalisés',
    service_private_desc: 'Cours particuliers avec des instructeurs expérimentés et avec le Double Champion du Monde d\'Équitation – Gilberto Filipe. Programme entièrement adapté à votre niveau et objectifs.',
    service_private_feat_1: 'Instructeur dédié',
    service_private_feat_2: 'Programme personnalisé',
    service_private_feat_3: 'Suivi individuel',
    service_private_feat_4: 'Flexibilité horaire',
    
    service_group_title: 'Cours en Groupe',
    service_group_short: 'Maximum 4 élèves par cours',
    service_group_desc: 'Cours en groupe avec jusqu\'à 4 élèves, favorisant l\'apprentissage collaboratif, la socialisation et l\'esprit d\'équipe dans un environnement amusant.',
    service_group_feat_1: 'Maximum 4 élèves',
    service_group_feat_2: 'Environnement social',
    service_group_feat_3: 'Apprentissage en équipe',
    service_group_feat_4: 'Prix accessible',
    

    service_rental_title: 'Location d\'Espace',
    service_rental_short: 'Événements et fêtes d\'anniversaire',
    service_rental_desc: 'Espace unique et accueillant pour événements spéciaux, fêtes d\'anniversaire et célébrations. Activités optionnelles avec chevaux incluses.',
    service_rental_feat_1: 'Espace privé',
    service_rental_feat_2: 'Décoration incluse',
    service_rental_feat_3: 'Activités optionnelles',
    service_rental_feat_4: 'Restauration disponible',
    
    service_owners_title: 'Propriétaires',
    service_owners_short: 'Réservations pour propriétaires',
    service_owners_desc: 'Service exclusif pour propriétaires de chevaux. Permet la réservation de créneaux horaires avec priorité secondaire par rapport aux élèves réguliers.',
    service_owners_feat_1: 'Horaires flexibles',
    service_owners_feat_2: 'Sous réserve de disponibilité',
    service_owners_feat_3: 'Maximum 6 élèves par session',
    service_owners_feat_4: 'Priorité aux élèves réguliers',
    
    // Bookings
    my_lessons: 'Mes Cours',
    new_booking: 'Nouvelle Réservation',
    payments: 'Paiements',
    select_service: 'Sélectionner le Service',
    select_plan: 'Sélectionner le Plan',
    select_date_time: 'Sélectionner Date et Heure',
    confirm_booking: 'Confirmer la Réservation',
    booking_confirmed: 'Réservation Confirmée!',
    
    // Shop
    shop_title: 'Boutique',
    featured_products: 'Produits en Vedette',
    search_products: 'Rechercher des produits...',
    sort_by: 'Trier par',
    price_low_high: 'Prix: Bas à Élevé',
    price_high_low: 'Prix: Élevé à Bas',
    name_az: 'Nom A-Z',
    no_products_found: 'Aucun produit trouvé',
    added_to_cart: 'Produit ajouté au panier!',
    all_categories_shop: 'Tous',
    add_to_cart: 'Ajouter au Panier',
    view_cart: 'Voir le Panier',
    checkout: 'Passer Commande',
    
    // Contact
    contact_title: 'Contact',
    get_in_touch: 'Contactez-nous',
    contact_subtitle: 'Vous avez une question ou souhaitez en savoir plus sur nos services? Nous sommes là pour vous aider!',
    name: 'Nom',
    email: 'Email',
    phone: 'Téléphone',
    message: 'Message',
    send_message: 'Envoyer Message',
    subject: 'Sujet',
    address: 'Adresse',
    opening_hours: 'Horaires',
    monday_friday: 'Lundi à Vendredi',
    your_name: 'Votre nom',
    your_email: 'Votre email',
    your_phone: 'Votre téléphone',
    your_message: 'Votre message',
    message_sent: 'Message envoyé!',
    
    // Reviews
    reviews: 'Avis',
    write_review: 'Écrire un Avis',
    rating: 'Note',
    review_title: 'Titre',
    review_comment: 'Commentaire',
    review_placeholder: 'Parlez-nous de votre expérience...',
    publish_review: 'Publier l\'Avis',
    sending: 'Envoi...',
    login_to_review: 'Connectez-vous pour évaluer',
    fill_all_fields: 'Remplissez tous les champs',
    review_sent: 'Avis envoyé! En attente d\'approbation.',
    verified_purchase: 'Achat vérifié',
    
    // Payments
    total_paid: 'Total Payé',
    pending: 'En Attente',
    penalties: 'Pénalités',
    payment_history: 'Historique des Paiements',
    no_payments: 'Aucun paiement enregistré',
    monthly_fee: 'Mensualité',
    due_date: 'Date d\'échéance',
    paid_on: 'Payé le',
    penalty_applied: 'Pénalité appliquée',
    payment_rules: 'Règles de Paiement',
    account_blocked: 'Compte Bloqué',
    debt_warning: 'Votre compte est bloqué en raison de dettes supérieures à 30€.',
    active_restrictions: 'Restrictions actives',
    no_new_bookings: 'Impossible de faire de nouvelles réservations',
    no_classes: 'Impossible de participer aux cours',
    no_competitions: 'Impossible de participer aux compétitions',
    no_club_representation: 'Impossible de représenter le club',
    total_debt: 'Dette Totale',
    pending_payments: 'Paiements en Attente',
    regularize_warning: 'Veuillez régulariser vos paiements pour éviter les pénalités.',
    amount_owed: 'Montant dû',
    overdue: 'En retard',
    min: 'min',
    max: 'Max.',
    from: 'Depuis',
    booking_confirmation_message: 'Votre réservation a été enregistrée. Nous vous avons envoyé un email de confirmation.',
    
    // Common
    continue: 'Continuer',
    back: 'Retour',
    cancel: 'Annuler',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
    search: 'Rechercher',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
    confirm: 'Confirmer',
    price: 'Prix',
    duration: 'Durée',
    date: 'Date',
    time: 'Heure',
    status: 'Statut',
    
    // Home Hero
    excellence_center: 'Centre Équestre d\'Excellence',
    world_champion_intro: 'Découvrez l\'art de l\'équitation avec',
    world_champion_name: 'Double Champion du Monde Gilberto Filipe',
    hero_description: 'Nous proposons des cours personnalisés et des expériences uniques avec les chevaux dans un environnement naturel et accueillant.',
    book_lesson: 'Réserver un Cours',
    know_services: 'Découvrir les Services',
    years_experience: 'Années d\'Expérience',
    students_trained: 'Élèves Formés',
    world_champion: 'Champion du Monde',
    
    // Services Preview
    our_services: 'Nos Services',
    equestrian_experiences: 'Expériences Équestres d\'Excellence',
    services_description: 'Des débutants aux cavaliers expérimentés, nous proposons des programmes personnalisés pour tous les âges et niveaux.',
    private_lessons: 'Cours Particuliers',
    private_lessons_desc: 'Cours individuels avec des moniteurs expérimentés ou avec le Double Champion du Monde Gilberto Filipe.',
    group_lessons: 'Cours en Groupe',
    group_lessons_desc: 'Cours avec jusqu\'à 4 élèves, favorisant l\'apprentissage collaboratif et la socialisation.',

    space_rental: 'Location d\'Espace',
    space_rental_desc: 'Espace unique pour événements, anniversaires et célébrations spéciales.',
    view_all_services: 'Voir Tous les Services',
    
    // About
    about_us: 'À Propos',
    excellence_tradition: 'Une Tradition d\'Excellence Équestre',
    about_description_1: 'Le Picadeiro Quinta da Horta est plus qu\'un centre équestre — c\'est un lieu où la passion des chevaux rencontre l\'excellence dans l\'enseignement. Situé dans la belle région d\'Alcochete, nous offrons un environnement naturel et paisible pour la pratique de l\'équitation.',
    about_description_2: 'nous développons des programmes personnalisés qui respectent le rythme de chaque élève, des débutants aux plus expérimentés.',
    contact_us: 'Contactez-nous',
    
    // CTA
    ready_to_start: 'Prêt à Commencer Votre',
    equestrian_journey: 'Aventure Équestre?',
    cta_description: 'Faites le premier pas vers une expérience unique avec les chevaux. Réservez votre premier cours d\'essai ou contactez-nous pour plus d\'informations.',
    call_now: 'Appeler Maintenant',
    trial_lesson: 'Cours d\'Essai',
    trial_lesson_desc: 'Essayez un cours d\'introduction et découvrez le monde de l\'équitation.',
    visit_facilities: 'Visite des Installations',
    visit_facilities_desc: 'Planifiez une visite pour découvrir notre espace et nos chevaux.',
    monthly_packages: 'Forfaits Mensuels',
    monthly_packages_desc: 'Découvrez nos plans avec conditions spéciales pour les élèves réguliers.',
    
    // Bookings
    bookings_area: 'Espace Réservations',
    bookings_login_message: 'Connectez-vous pour gérer vos réservations, confirmer votre présence et consulter les paiements.',
    login_or_register: 'Se Connecter ou S\'inscrire',
    hello: 'Bonjour',
    manage_bookings_subtitle: 'Gérer vos cours, confirmer votre présence et consulter les paiements',
    my_classes: 'Mes Cours',
    new_booking: 'Nouvelle Réservation',
    payments: 'Paiements',
    filters: 'Filtres',
    
    // Gallery
    our_gallery: 'Notre Galerie',
    gallery_title: 'Moments Inoubliables',
    gallery_subtitle: 'Découvrez les meilleurs moments de notre centre équestre à travers des images',
    all_categories: 'Toutes',
    classes: 'Cours',
    events: 'Événements',
    horses: 'Chevaux',
    facilities: 'Installations',
    competitions: 'Compétitions',
    others: 'Autres',
    no_images: 'Aucune image trouvée',

    // Footer
    quick_links: 'Liens Rapides',
    footer_description: 'Centre équestre d\'excellence à Alcochete, proposant des cours d\'équitation et des expériences uniques avec les chevaux.',
    
    // Cart & Checkout
    cart_title: 'Panier',
    your_cart: 'Votre Panier',
    cart_empty: 'Votre panier est vide',
    continue_shopping: 'Continuer les Achats',
    quantity: 'Quantité',
    subtotal: 'Sous-total',
    discount: 'Réduction',
    shipping: 'Livraison',
    total: 'Total',
    apply_coupon: 'Appliquer le Coupon',
    coupon_code: 'Code du Coupon',
    apply: 'Appliquer',
    proceed_checkout: 'Passer Commande',
    checkout_title: 'Finaliser la Commande',
    shipping_address: 'Adresse de Livraison',
    street: 'Rue',
    city: 'Ville',
    postal_code: 'Code Postal',
    country: 'Pays',
    place_order: 'Passer Commande',
    order_success: 'Commande Passée!',
    order_confirmation: 'Votre commande a été reçue et sera traitée sous peu.',
    order_number: 'Numéro de Commande',
    back_to_shop: 'Retour à la Boutique',
    remove: 'Supprimer',
    removed_from_cart: 'Produit retiré du panier',
    products: 'Produits',
    order_summary: 'Résumé',
    coupon_applied: 'Coupon',
    applied: 'appliqué',
    free: 'Gratuit',
    free_shipping_note: 'Livraison gratuite pour commandes supérieures à 50€',
    processing: 'Traitement...',
    back_to_cart: 'Retour au Panier',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'pt';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}